Configs: &Default
  Version: 2
  AppName: Loymax Loyalty
  AgreementSettings:
    Content: offer.html
  ServerSettings:
    VerifyPhoneCodeLength: 6
    ForceDisableInputSocial: False
  Analytics:
    Google: 
      Enable: true
  CachePolicyEnabled: False
  ResendCodeConfirmTime: 60 #Время ожидания для повторной отправки кода подтверждения (секунды)
  AnonymVirtualCard: False #Виртуальная карта для анонима 
  ShowOptions:
    ProfileCardViewModel: OnlyAuth #Отображать в меню "Моя карта" All or OnlyAuth
    PersonalOffersViewModel: OnlyAuth #Отображать в меню "Персональные акции" OnlyAuth or Never
    PersonalGoodsViewModel: OnlyAuth #Отображать в меню "Любимые товары" OnlyAuth or Never
  Localization:
    Enable: True #Подключение локализации
    ViewLocalization: True #Отображение стартового экрана с выбором языка при первом запуске приложения

Development:
  <<: *Default
  LoymaxEndpoint: 
    AppUrl: https://demo.loymax.tech/publicapi/
    ClientId: ""
    PublicKey: ""
    OfferId: "required"
    PrivacyId: "required"
  HockeyApp: 
    AppKey:
      Android: False
      Ios: False
    EnableCrashManager: False
  PushNotification: 
    Enable: False

Staging:
  <<: *Default
  LoymaxEndpoint: 
    AppUrl: https://demo.loymax.tech/publicapi/
    ClientId: ""
    PublicKey: ""
    OfferId: "required"
    PrivacyId: "required"
  HockeyApp:
    AppKey:
      Android: "required"
      Ios: "required"
    EnableCrashManager: True
  PushNotification: 
    Enable: True

Production:
  <<: *Default
  LoymaxEndpoint:
    AppUrl: https://demo.loymax.tech/publicapi/
    ClientId: ""
    PublicKey: ""
    OfferId: "required"
    PrivacyId: "required"
  HockeyApp: 
    AppKey:
      Android: "required"
      Ios: "required"
    EnableCrashManager: True
  PushNotification: 
    Enable: True